### PR TITLE
BULLSHIT_VALUES is used as a set so might as well be one.

### PR DESCRIPTION
**Pull request by yxhuvud**

### CODE REVIEW

**Comment by dudo** [comment]
big fan... this should speed it up a bit, as well.

**Review by dudo — APPROVED** [review]

**Comment by alexford** [comment]
This is better, but I think https://github.com/alexford/is_bullshit/pull/10 is an even better approach. Thoughts?

**Comment by yxhuvud** [comment]
I guess it would make sense that different classes know their own bullshit.

**Comment by alexford** [comment]
Closing in favor of https://github.com/alexford/is_bullshit/pull/10

**Pull request closed without merging**
