### PR TITLE
oo is bs

### PR DESCRIPTION
**Pull request by Cohen-Carlisle**
bro do you % 2 == 0 oo?

Closes https://github.com/alexford/is_bullshit/issues/3

### CODE REVIEW

**Comment by alexford** [comment]
Now this...  this is a quality PR.

**Comment by alexford** [comment]
I like this approach rather than a "dumb" Hash or set. I'm considering merging this, and/but it will break a few of the other open PRs.

**Comment by tom-lord** [comment]
+1 for this. Improving efficiency like [this](https://github.com/alexford/is_bullshit/pull/15) is a bullshit premature optimisation.

...Or maybe that means you *should* merge that PR in favour of this one?

**Comment by dudo** [comment]
love this PR

**Pull request merged**
